In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
df = pd.read_csv("insurance_data.csv")
df.head()

   AGENCY_ID  PRIMARY_AGENCY_ID  ... PL_BOUND_CT_TRANSACTNOW PL_QUO_CT_TRANSACTNOW
0          3                  3  ...                       0                     0
1          3                  3  ...                       0                     0
2          3                  3  ...                       0                     0
3          3                  3  ...                       0                     0
4          3                  3  ...                       0                     0

[5 rows x 49 columns]

In [9]:
df.shape

(213328, 49)

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age', 'affordability']], df.bought_insurance, test_size = 0.2, random_state = 25)

KeyError: "None of [Index(['age', 'affordability'], dtype='object')] are in the [columns]"

In [10]:
len(X_train)

NameError: name 'X_train' is not defined

In [ ]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age']/100

X_train_scaled = X_test.copy()
X_train_scaled['age'] = X_train_scaled['age']/100

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape = (2,), activation = 'sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile

In [ ]:
def gradient_descent(age, affordability, y_true, epochs, loss_threshold):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)

    for i in range(epochs):
        weighted_sum = w1*age + w2*affordability + bias
        y_predicted = sigmoid_numpy(weighted_sum)

        loss = log_loss(y_true, y_predicted)

        w1d = (1/n)*np.dot(np.transpose(age), (y_predicted-y_true))
        w2d = (1/n)*np.dot(np.transpose(affordability), (y_predicted-y_true))

        bias_d = np.mean(y_predicted-y_true)

        w1 = w1-rate*w1d
        w2 = w2-rate*w2d
        bias = bias - rate*bias_d

        print(f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

        if loss<=loss_threshold:
            break

    return w1,w2,bias